 ## Libraries in Python:
 
 * Numpy 
 * Pandas
 * Matplotlib
 


### Numpy :


#### What is Numpy?

* Numpy in python is a library ,used to create an array.
* It also has functions for working in domain of linear algebra,fourier Transform and Matrices,stastics.
* Numpy --- Numerical Python.

#### Why we are using Numpy?

* In python lists take more memory space for storing the elements and arrays take very less space.
* Lists take more time to execute when compared to arrays.
* Array can be used in datascience very frequently.




In [1]:
#### How to import our Numpy library?

import numpy as np ### import library_name as alias_name


In [2]:
### creating an array :

a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [3]:
type(a)

numpy.ndarray

In [4]:
### checking the version of library:

print(np.__version__)

1.16.2


In [5]:
### 1-D dimensional array:
#### 1-D array is also called as Uni-Dimensional array.

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [6]:
### 2-D array:

np.array([[1,2,3,4,5],[7,8,9,10]])


array([list([1, 2, 3, 4, 5]), list([7, 8, 9, 10])], dtype=object)

In [9]:
### 3-D array:

print(np.array([[[1,2,3,4,5],[7,8,9,10]],[[1,2,3,4,5],[7,8,9,10]]]))

[[list([1, 2, 3, 4, 5]) list([7, 8, 9, 10])]
 [list([1, 2, 3, 4, 5]) list([7, 8, 9, 10])]]


In [18]:
### checking the dimensions:

a = np.array(45)
print(a,a.ndim)
b = np.array([1,2,3,4,5,6])
print(b,b.ndim)
c = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(c,c.ndim)
d = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
print(d,d.ndim)

45 0
[1 2 3 4 5 6] 1
[[1 2 3 4 5]
 [1 2 3 4 5]] 2
[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]] 3


In [25]:
## Accessing elements using index values:
## 1-d array

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [30]:
a[3] + a[0] ### adding elements at different indices: 1+4 =5

5

In [32]:
### 2-d array:

b = np.array([[1,2,3,4,5],[1,2,3,4,5]])
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [36]:
print("middle element from first row",b[0,2]) ### rowindex,elementindex

middle element from first row 3


In [38]:
print("last element from last row",b[1,-1]) 
b[1,4]

last element from last row 5


5

In [ ]:
array([[1, 2, 3, 4, 5], ------ 0
       [1, 2, 3, 4, 5]]) ----- 1

b[1,-1]

In [49]:
### 3-d array:

c = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[10,9,8,7,6],[5,4,3,2,1]]])

c[0,1,2]


8

In [52]:
c[1,0,0]

10

In [59]:
#### Slicing in Arrays:

## 1-d array

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [60]:
a[1:3] ### 1-d slicing

array([2, 3])

In [62]:
a[0:3:2]  ### step slicing

array([1, 3])

In [63]:
a[0:3]

array([1, 2, 3])

In [67]:
### slicing of 2-d array:


b = np.array([[1,2,3,4,5],[1,2,3,4,5]])
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [66]:
b[0,2:]

array([3, 4, 5])

In [68]:
b[1,:3]

array([1, 2, 3])

In [69]:
### slicing to get column values:

b[0:2,2]

array([3, 3])

In [71]:
b[0:,2:]

array([[3, 4, 5],
       [3, 4, 5]])

In [72]:
b[0:,0]

array([1, 1])

In [76]:
### creating arrays with a particular datatype:

a = np.array([1,2,3,4],dtype = 'S')
a

array([b'1', b'2', b'3', b'4'], dtype='|S1')

 * i -- integer 
 * S -- string
 * f -- float
 * b -- boolean
 * O -- object
 * c -- complex float
 
 


In [77]:
a = np.array([1,2,3,4],dtype = 'f')
a

array([1., 2., 3., 4.], dtype=float32)

In [84]:
a = np.arange(1,10) ### arange is used to create array with particular range values

In [89]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [92]:
help(b.argmax)

Help on built-in function argmax:

argmax(...) method of numpy.ndarray instance
    a.argmax(axis=None, out=None)
    
    Return indices of the maximum values along the given axis.
    
    Refer to `numpy.argmax` for full documentation.
    
    See Also
    --------
    numpy.argmax : equivalent function



In [93]:
b.argmax()  ### maximum values index


4

In [95]:
b.max()

5

In [96]:
np.ones((2,2)) ### 1 matrix

array([[1., 1.],
       [1., 1.]])

In [101]:
np.zeros((2,2)) ### 0 matrix


array([[0., 0.],
       [0., 0.]])

In [102]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [106]:
b = a.reshape((2,3))

In [107]:
np.ones_like(b)

array([[1, 1, 1],
       [1, 1, 1]])

In [108]:
c = np.full((3,2),2)
c

array([[2, 2],
       [2, 2],
       [2, 2]])

In [110]:
np.empty([1,2])

array([[  2.00000047, 512.00012255]])

In [111]:
np.empty([1,3])

array([[ 1.17336254e-311,  0.00000000e+000, -4.94065646e-324]])

In [113]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [116]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [118]:
a.transpose()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [120]:
b.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [121]:
np.sum(a)

3.0

In [124]:
np.sqrt(b)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [125]:
np.log(b)

C:\Users\Niharikaa\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791]])

In [128]:
np.max(b)

5

In [129]:
np.min(b)

0

In [132]:
c = np.random.randn(7)

In [133]:
c

array([ 1.54358488, -1.23893886,  0.1805833 ,  1.1179278 , -1.09182736,
       -1.74451847,  0.04808072])

In [136]:
c. cumsum(axis = 0)

array([ 1.54358488,  0.30464602,  0.48522932,  1.60315712,  0.51132975,
       -1.23318871, -1.18510799])

In [140]:
### slicing for 
c = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[10,9,8,7,6],[5,4,3,2,1]]])
c

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[10,  9,  8,  7,  6],
        [ 5,  4,  3,  2,  1]]])

In [139]:
c[0:,1,2:4]

array([[8, 9],
       [3, 2]])

In [145]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])